Test / Fix
Force entity to be saved.

```
[ERROR] Failures:
[ERROR]   GeonetRepositoryTest.testBatchUpdateAttributes:125 expected:<[Updated DataElem]> but was:<[<md>metadata12</md>]>
[ERROR]   MetadataRepositoryTest.testIncrementPopularity:95 expected:<33> but was:<32>
```

We don't really know why this is required and how it is linked to the Joda removal.